# Generated by Django 4.0.5 on 2022-07-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactus',
            new_name='Contact',
        ),
    ]
